spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filter:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path= /auth/**
          filter:
            - RewritePath=/auth(?<segment>/?.*), $\{segment}
            
            
        - id: task-management-service
          uri: http://localhost:8083
          predicates:
            - Path=/task/**
          filter:
            - RewritePath=/task(?<segment>/?.*), $\{segment}
          
        - id: email-service
          uri: http://localhost:8084
          predicates:
            - Path=/email/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

server:
  port: 8080
