spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /emp/**
          filter:
            - RewritePath=/emp(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path= /auth/**
          filter:
            - RewritePath=/authentication(?<segment>/?.*), $\{segment}
            
            
        - id: task-management-service
          uri: http://localhost:8083
          predicates:
            - Path=/task/**
          filter:
            - RewritePath=/taskmgmt(?<segment>/?.*), $\{segment}
          
        - id: email-service
          uri: http://localhost:8084
          predicates:
            - Path=/email/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

server:
  port: 8080
